version: '2.2'

volumes:
    mariadb-volume:
    nova-images:

services:
    mariadb:
        image: 'mariadb:10.1.22'
        env_file: '../config/config'
        environment:
            MARIADB_EXTRA_FLAGS: '--max-connections=8192'
        hostname: 'mariadb'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes: 
            - 'mariadb-volume:/var/lib/mysql'

    rabbitmq:
        image: 'rabbitmq:3'
        env_file: '../config/config'
        hostname: '${CONTROL_HOST}'
        ports:
            - '5672:5672'
        expose:
            - '5672'

    keystone-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-keystone:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'keystone'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '5000:5000'
            - '35357:35357'
        expose:
            - '5000'
            - '35357'
        sysctls:
            net.core.somaxconn: 2048
        links:
            - 'mariadb'
            - 'rabbitmq'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/keystone:/scripts/keystone'
        command: '/scripts/keystone/start-keystone-api.sh'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'

    swift-proxy:
        image: '${DOCKERHUB_NAMESPACE}/locistack-swift:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'swift'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        privileged: true
#        network_mode: 'host'
        ports:
            - '8888:8888'
        expose:
            - '8888'
        volumes:
            - '/dev/loop1:/dev/loop1'
            - './scripts/common:/scripts/common'
            - './scripts/swift:/scripts/swift'
        networks:
            swiftnet:
                ipv4_address: '172.16.16.16'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        command: '/scripts/swift/start-service.sh'


    glance-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-glance:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        privileged: true
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '9292:9292'
        expose:
            - '9292'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/glance:/scripts/glance'
        command: '/scripts/glance/start-glance-api.sh'

    cinder-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-cinder:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '8776:8776'
        expose:
            - '8776'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/cinder:/scripts/cinder'
        command: '/scripts/cinder/start-cinder-api.sh'

    cinder-scheduler:
        image: '${DOCKERHUB_NAMESPACE}/locistack-cinder:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/cinder:/scripts/cinder'
        command: '/scripts/cinder/start-cinder-scheduler.sh'

    cinder-volume:
        image: '${DOCKERHUB_NAMESPACE}/locistack-cinder:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        network_mode: 'host'
        privileged: true
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'cinder-scheduler'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/cinder:/scripts/cinder'
            - '/dev:/dev'
            - '/run/:/run/:shared'
            - '/etc/localtime:/etc/localtime:ro'
            - '/lib/modules:/lib/modules:ro'
        ports:
            - 3260:3260
        command: '/scripts/cinder/start-cinder-volume.sh'

    neutron-server:
        image: '${DOCKERHUB_NAMESPACE}/locistack-neutron:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'neutron-server'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '9696:9696'
        expose:
            - '9696'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
        command: '/scripts/neutron/start-neutron-server.sh'

    neutron-linuxbridge-agent:
        image: '${DOCKERHUB_NAMESPACE}/locistack-neutron:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'neutron-linuxbridge-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - ALL
        sysctls:
            net.ipv4.conf.all.promote_secondaries: 1
            net.ipv4.ip_forward: 1
            net.ipv4.conf.all.rp_filter: 0
            net.ipv4.conf.default.rp_filter: 0
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
        command: '/scripts/neutron/start-neutron-linuxbridge-agent.sh'

    neutron-dhcp-agent:
        image: '${DOCKERHUB_NAMESPACE}/locistack-neutron:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'neutron-dhcp-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - 'ALL'
            - 'NET_ADMIN'
        sysctls:
            net.ipv4.conf.all.promote_secondaries: 1
            net.ipv4.ip_forward: 1
            net.ipv4.conf.all.rp_filter: 0
            net.ipv4.conf.default.rp_filter: 0
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
        command: '/scripts/neutron/start-neutron-dhcp-agent.sh'

    neutron-metadata-agent:
        image: '${DOCKERHUB_NAMESPACE}/locistack-neutron:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'neutron-metadata-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - 'NET_ADMIN'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
        command: '/scripts/neutron/start-neutron-metadata-agent.sh'

    neutron-l3-agent:
        image: '${DOCKERHUB_NAMESPACE}/locistack-neutron:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'neutron-l3-agent'
        privileged: true
        network_mode: 'host'
        cap_add:
            - 'NET_ADMIN'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/neutron:/scripts/neutron'
        command: '/scripts/neutron/start-neutron-l3-agent.sh'

    placement-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-placement:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'placement-api'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '8778:8000'
        expose:
            - '8000'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/placement:/scripts/placement'
        command: '/scripts/placement/start-placement-api.sh'

    nova-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'nova-api'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '8774:8774'
        expose:
            - '8774'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
        command: '/scripts/nova/start-nova-api.sh'

    nova-metadata:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'nova-api'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '8775:8775'
        expose:
            - '8775'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
        command: '/scripts/nova/start-nova-metadata.sh'

    nova-conductor:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'nova-conductor'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
        command: '/scripts/nova/start-nova-conductor.sh'

    nova-scheduler:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'nova-scheduler'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
        command: '/scripts/nova/start-nova-scheduler.sh'

    nova-novncproxy:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'nova-novncproxy'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '6080:6080'
        expose:
            - '6080'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
        command: '/scripts/nova/start-nova-novncproxy.sh'

    libvirt:
        image: '${DOCKERHUB_NAMESPACE}/locistack-libvirt:${OPENSTACK_RELEASE}-${DISTRO}'
        privileged: 'true'
        network_mode: 'host'
        pid: 'host'
        ipc: 'host'
        user: 'root'
        volumes:
            - '/etc/localtime:/etc/localtime'
            - '/lib/modules:/lib/modules'
            - '/run/:/run/'
            - '/dev:/dev'
            - '/sys/fs/cgroup:/sys/fs/cgroup'
            - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'
            - '/var/run/libvirt:/var/run/libvirt'
            - '/var/lib/nova:/var/lib/nova'
        command: '/start-libvirt.sh'

    nova-compute:
        image: '${DOCKERHUB_NAMESPACE}/locistack-nova:${OPENSTACK_RELEASE}-${DISTRO}'
        privileged: 'true'
        env_file: '../config/config'
        hostname: 'nova-compute'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/nova:/scripts/nova'
            - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'
            - '/var/lib/nova:/var/lib/nova'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'nova-api'
        command: '/scripts/nova/start-nova-compute.sh'

    post-install:
        image: '${DOCKERHUB_NAMESPACE}/locistack-openstack:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/post-install:/scripts/post-install'
        command: '/scripts/post-install/post-install.sh'

    horizon:
        image: '${DOCKERHUB_NAMESPACE}/locistack-horizon:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        network_mode: 'host'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/horizon:/scripts/horizon'
        command: '/scripts/horizon/start_horizon.sh'


networks:
    swiftnet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.16.0/24
