version: '2.2'

volumes:
    ironic-imagedata-volume:

services:
    dnsmasq-ipmi:
        image: '${DOCKERHUB_NAMESPACE}/locistack-dnsmasq:master-centos'
        env_file: '../config/config'
        ports:
            - '53:53'
            - '53:53/udp'
        expose:
            - '53'
        cap_add:
            - 'NET_ADMIN'
        network_mode: 'host'
        volumes:
            - './scripts/dnsmasq:/scripts/dnsmasq'
        command: '/scripts/dnsmasq/start_dnsmasq.sh'

    ironic-api:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'ironic-api'
        network_mode: 'host'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        ports:
            - '6385:6385'
        expose:
            - '6385'
        volumes:
            - 'ironic-imagedata-volume:/imagedata'
            - './scripts/common:/scripts/common'
            - './scripts/ironic:/scripts/ironic'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'neutron-server'
            - 'glance-api'
            - 'swift-proxy'
        command: '/scripts/ironic/start-ironic-api.sh'

    ironic-agent:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        extra_hosts:
            - "${CONTROL_HOST}:${CONTROL_HOST_IP}"
        network_mode: 'host'
        volumes:
            - './scripts/common:/scripts/common'
            - './scripts/ironic:/scripts/ironic'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'keystone-api'
            - 'glance-api'
            - 'swift-proxy'
        command: '/scripts/ironic/upload-agent.sh'

    ironic-conductor:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'ironic-conductor'
        volumes:
            - 'ironic-imagedata-volume:/imagedata'
            - './scripts/common:/scripts/common'
            - './scripts/ironic:/scripts/ironic'
            - '/dev:/dev:rw'
        privileged: true 
        network_mode: 'host'
        ports:
            - '3260:3260'
        expose:
            - '3260'
        depends_on:
            - 'mariadb'
            - 'rabbitmq'
            - 'ironic-api'
        command: '/scripts/ironic/start-ironic-conductor.sh'

    ironic-tftp:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'ironic-tftp'
        ports:
            - '69:69/udp'
            - '69:69'
        expose:
            - '69'
            - '69/udp'
        volumes:
            - 'ironic-imagedata-volume:/imagedata'
            - './scripts/ironic:/scripts/ironic'
            - './scripts/common:/scripts/common'
        command: '/scripts/ironic/start-ironic-tftp.sh'

    ironic-nginx:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'ironic-nginx'
        extra_hosts:
            - '${CONTROL_HOST}:${CONTROL_HOST_IP}'
        ports: 
            - '8080:8080'
        expose:
            - '8080'
        volumes:
            - 'ironic-imagedata-volume:/imagedata'
            - './scripts/ironic:/scripts/ironic'
            - './scripts/common:/scripts/common'
        command: '/scripts/ironic/start-ironic-nginx.sh'

    ironic-iscsi:
        image: '${DOCKERHUB_NAMESPACE}/locistack-ironic:${OPENSTACK_RELEASE}-${DISTRO}'
        env_file: '../config/config'
        hostname: 'ironic-iscsi'
        privileged: true
        network_mode: 'host'
        volumes:
            - '/dev/disk:/dev/disk'
            - './scripts/ironic:/scripts/ironic'
            - './scripts/common:/scripts/common'
        command: '/scripts/ironic/start-ironic-iscsid.sh'

    post-install:
        command: '/scripts/post-install/post-install-ironic.sh'
